### ISSUE TITLE
Recurring Meeting Collapsible (frontend)

### ISSUE THREAD

**Issue by tunile943** [cornellh4i/ithaca-recovery#61]
**Branches:** `atoms/spinner-input` + `molecules/recurring-meeting`

### Task at Hand
`atoms/spinner-input`
1. View the [High Fidelity](https://www.figma.com/design/jXa3CEMdz5YRrGTknEznxz/Recovery?node-id=886-20373&m=dev) for the Spinner Input. Reference:

![Image](https://github.com/user-attachments/assets/0b80e819-6651-4997-9688-335019664ea5)
 
2. Implement input spinner with the below props:
```
interface InputSpinnerProps {
  label?: string;
  value: number;  // Default value of the spinner
  min?: number; 
  max?: number;
  step?: number; 
  onChange: (value: number) => void; 
  underlineOnFocus?: boolean;
  disabled?: boolean;
  readOnly?: boolean;
  error?: string; 
}
```

3. Confirm that your code and pull request follow the [Pull Request Checklist](https://h4i.notion.site/Pull-Request-Checklist-37c67d3b6a9b488f8339f32116bfb12c). 
### Acceptance Criteria
- [ ] Create reusable atomic component which can be used in different contexts.
- [ ] The component is styled properly per High-Fidelity.

`molecules/recurring-meeting`
1. View the [High Fidelity](https://www.figma.com/design/jXa3CEMdz5YRrGTknEznxz/Recovery?node-id=1034-19522&m=dev) for the Recurring Meeting collapsible. Reference:

![Image](https://github.com/user-attachments/assets/6a8fc5ba-bc73-4e21-a2c9-89349aa6e1d2)
 
2. Implement the collapsible with the following specification:
- "This meeting is recurring." should be a checkbox atom. When it is checked, it says "This meeting is recurring". When it's not, it should say "This meeting is not recurring".
- When "This meeting is recurring", the frequency inputs should pop up. When "This meeting is not recurring", none of the below frequency inputs should pop up.
- "Every 1 week" should be an input spinner and a dropdown
- "On S M T W T F S" should be a group of button
-  "Ends" should be a radio group

3. Confirm that your code and pull request follow the [Pull Request Checklist](https://h4i.notion.site/Pull-Request-Checklist-37c67d3b6a9b488f8339f32116bfb12c). 
### Acceptance Criteria
- [ ] Confirm that design matches Design System (and as described above).

### Notes
- No need to connect to backend yet, that will be for another ticket.
