### ISSUE TITLE
Atoms UI Fix (Frontend)

### ISSUE THREAD

**Issue by tunile943** [cornellh4i/ithaca-recovery#73]
**Branches:** `atoms/UI-Fix`

### Task at Hand
1. Add the following features for atoms. The Figma for the New Meeting Form can be found [here](https://www.figma.com/design/jXa3CEMdz5YRrGTknEznxz/Recovery?node-id=1034-19105&m=dev). 
- Make note that all labels from now on should accept SVG, we are phasing out MUI-Icons. In /public, create /svg. Put all relevant icons from the bottom row into /svg folder. There should already be some svg file in /public already for reference.
<img width="555" alt="image" src="https://github.com/user-attachments/assets/8095596e-7fe0-4153-a903-4ef332e209da">

- Implement in-line atoms/TextField (so TextField can either takes a full line at full size with text size of 24px, or with a label with text size of 18px). Subsequently, add an Email text field with label to the new meeting form inside CalendarSidebar/index.tsx

<img width="295" alt="image" src="https://github.com/user-attachments/assets/81b4684f-cbd7-43f4-9e84-87558bc8ac18">

<img width="207" alt="image" src="https://github.com/user-attachments/assets/11130542-1e05-418f-b304-0a18fe1c8b50">

- Add label for atoms/upload. Subsequently, add label for the upload form inside CalendarSidebar/index.tsx

<img width="324" alt="image" src="https://github.com/user-attachments/assets/029d3f42-ef8e-41fc-b007-03b824c39c34">

- Add highlight to Date/TimePicker when chosen. Refer to TextField/index.tsx for how we did this.
- Add Hybrid/In Person/Remote buttons to New Meeting Form (right below Meeting Title Textfield). Make sure that only one button can be chosen at a time. Hybrid is the default option. Make sure to put this inside the New Meeting Form in Calendar Sidebar too. 

2. Confirm that your code and pull request follow the [Pull Request Checklist](https://h4i.notion.site/Pull-Request-Checklist-37c67d3b6a9b488f8339f32116bfb12c). 
### Acceptance Criteria

- [x] Add SVG support for labels.
- [x] Implement in-line atoms/TextField (so TextField can either takes a full line at full size 24px, or with a label at 18px)
- [x] Add label for atoms/upload
- [x] Add highlight to Date/TimePicker
- [x] Add Hybrid/In Person/Remote buttons to New Meeting Form

### Notes
-
