### ISSUE TITLE
View Recurring Meeting (Fullstack)

### ISSUE THREAD

**Issue by tunile943** [cornellh4i/ithaca-recovery#90]
**Branch:** `view-recurring-meeting-fullstack`

### Task at Hand
1. In `util/models.ts`, add the following props to IMeeting:

```
// Recurrence-related properties
  recurrenceId: string; // Shared across all instances in the recurrence group
  weeklyFrequency?: number; // How often it occurs (1 = weekly, 2 = every other week, etc.)
  recurrenceEndOn?: Date | null; // Optional: The date when the recurrence ends
  recurrenceEndAfter?: number | null; // Optional: The number of occurrences after which it ends
```

2. Modify create new meeting function in CalendarSidebar to support recurring meeting. 

3. Edit `organisms/DailyView/index.ts` to support viewing recurring meeting. 

4. Confirm that your code and pull request follow the [Pull Request Checklist](https://h4i.notion.site/Pull-Request-Checklist-37c67d3b6a9b488f8339f32116bfb12c). 

### Acceptance Criteria
- [x] Add recurrenceId, weeklyFrequency, recurrenceEndOn, and recurrenceEndAfter properties to IMeeting in util/models.ts.
- [x] createNewMeeting in CalendarSidebar supports creating recurring meetings with the above fields and validates conflicting recurrence settings.
- [ ] DailyView renders recurring meetings on appropriate days based on weeklyFrequency, recurrenceEndOn, and recurrenceEndAfter.
- [ ] Verify recurring meetings can be created, saved, and displayed correctly.
- [ ] Ensure PR follows the Pull Request Checklist.

### Notes
-
